travis:
  secure:
    BINSTAR_TOKEN: nijzc65LEXqHHldp2VF6HPo0yMpqUCLkwU+2NsnMyPUKcf5bEeU9BqwQpKxY+hp6T8JZ28zhMjRwacdCySp173vnuRrndeJj++W48VYNQ9Xksx8mEB/3LYZuMc32XZJpiqq/ghrI73AC5jm/b0jJUTRin0TB4AojGh07ey/vF9oCbgU3pIQ6uVGVs9LxZeExRfvKKoapiJrbGHbMVOiqZERXv5Is/e04OTZIasO8Kofe7zkGAw/Lmhjhkw0DkLDwJxdL4nvMrV+nutGig/K1DFn3+KPlySpu3icbEGLms0TLOOhC+1FoRPsqqVb4hki8xNyIdB/Zjnp773IbODPIs7LJrDipk39oJfHRtaMxBokB1k8uMBAk/Q60GfBOQtGSradlHuMf9kFAK46TGpenPlQu0BZ8tc5gA/NKIKQYix71pfPmtl1C/3SSWnSpFAVsH0thlGcaKa0SWil7eAFdaIFnKLySr7OIdQL44r/U3yUWo2WKrv/zXj1oXcggzYKGBsHy5M51CEBkf3sHkqN1wKHHYvmK9Sx/393NMskeWw+lPc4XgeO8wH+N76zWLW/M216bVrZn1mUE9JHElpd0iskP168MnqxeTjUVJGz8nwD3t6BZoKs5N/H2Jczy0IPAHa+jOOhmGy7NrFX+e626Gp5Ml9XXOrAvoufQpMqHoQU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
